#Sergey
m3tro1d/entrepresenteur pull request #24
Opened 2021-11-04 08:46 UTC by NoSiReapo

Вёрстка визуала компонента slidepanel

2021-11-04 13:09 UTC, m3tro1d requested changes

2021-11-04 13:09 UTC, m3tro1d commented on src/components/slidepanel/SlidePanel.css
> +.b-slidepanel__slide
Зачем везде префиксы `b-`? Что это значит?

2021-11-04 13:09 UTC, m3tro1d commented on src/components/slidepanel/images/dots_orange.svg
> +<svg width="535.5" height="535.5" xmlns="http://www.w3.org/2000/svg">
Ты верстаешь в стиле статичных страниц, что совсем не подходит под парадигмы реакта. Эта SVGшка должна быть отдельным компонентом, а SlidePanel содержал бы в себе, например, компонент SlideBlock, в нем уже SlideThumbnail.

2021-11-05 06:32 UTC, NoSiReapo commented on src/components/slidepanel/SlidePanel.css
> +.b-slidepanel__slide
блок слайдпанель

2021-11-05 06:34 UTC, NoSiReapo commented on src/components/slidepanel/images/dots_orange.svg
> +<svg width="535.5" height="535.5" xmlns="http://www.w3.org/2000/svg">
я в hover её запихну, так лучше будет

2021-11-06 11:20 UTC, m3tro1d commented on src/components/slidepanel/SlidePanel.css
> +.b-slidepanel__slide
> блок слайдпанель

Если так обозначать классы, будет то же самое, что и венгерская нотация. Сайдпанель - это и так самостоятельный блок, поэтому префиксы вообще не нужны.

2021-11-14 10:37 UTC, merged